/* ============================================================
   LESSONS DATA — the content behind the lesson player
   ------------------------------------------------------------
   HOW THE CATALOG AND LESSONS RELATE:
   levels-data.js (or the admin-edited copy) describes COURSES:
   A1 · Speaking has 4 units. This file holds the actual LESSON
   you open when you start a unit.

   TWO KINDS OF LESSON:
   1. AUTHORED (below) — hand-written: objectives, vocabulary,
      sections, a quiz. These are the showcase lessons.
   2. OUTLINE (generated by js/lesson.js) — every unit that has
      no authored lesson yet still opens a real page: goals
      pulled from the catalog, the grammar focus, and a concrete
      practice task. Honest, never a dead link.

   KEY: level + "|" + skill + "|" + unit index (0-based).
   The index matches the unit order in the catalog.
   ============================================================ */

const LESSON_LIBRARY = [

    /* ---------------- A1 · Speaking · unit 1 ---------------- */
    {
        level: "A1", skill: "Speaking", unit: 0,
        title: "Hello & goodbye — greetings that open doors",
        minutes: 12,
        intro: "The first ten seconds of any conversation. Get these right and people keep talking.",
        objectives: [
            "Greet someone at any time of day",
            "Say goodbye without sounding abrupt",
            "Answer “How are you?” like a native, not a textbook"
        ],
        vocab: [
            { word: "Good morning", meaning: "before ~12:00" },
            { word: "Good afternoon", meaning: "12:00 – ~18:00" },
            { word: "Good evening", meaning: "after ~18:00" },
            { word: "See you later", meaning: "friendly goodbye" },
            { word: "Take care", meaning: "warm goodbye" }
        ],
        sections: [
            {
                type: "text",
                title: "The three clocks",
                body: "English greetings follow the sun. Morning before noon, afternoon until early evening, evening after that. If you get it wrong, nobody is offended — but getting it right makes you sound fluent immediately."
            },
            {
                type: "tip",
                title: "The “How are you?” trap",
                body: "“How are you?” is usually a greeting, not a question. The natural answer is short: “Good, thanks — you?” Save the long answer for when someone actually asks about your day."
            },
            {
                type: "practice",
                title: "60-second drill",
                body: "Record yourself greeting three different people: a friend at 9 AM, a teacher at 4 PM, a neighbour at 8 PM. Listen back — did the greeting match the clock?"
            }
        ],
        quiz: {
            question: "It's 8 PM and you meet your neighbour. What do you say?",
            options: ["Good morning", "Good afternoon", "Good evening"],
            answer: 2,
            explain: "After roughly 6 PM, English switches to “Good evening”."
        }
    },

    /* ---------------- A1 · Writing · unit 1 ---------------- */
    {
        level: "A1", skill: "Writing", unit: 0,
        title: "Letters & sounds — spelling your world",
        minutes: 14,
        intro: "English spelling is a puzzle. This lesson gives you the pieces that matter first.",
        objectives: [
            "Spell your name and address out loud correctly",
            "Know the difference between letter names and sounds",
            "Use capital letters like an English writer"
        ],
        vocab: [
            { word: "A – E – I – O – U", meaning: "the five vowel letters" },
            { word: "capital letter", meaning: "ABC, not abc — names, cities, “I”" },
            { word: "double", meaning: "two of the same letter (Lloyd → double L)" }
        ],
        sections: [
            {
                type: "text",
                title: "Letters vs. sounds",
                body: "The letter is a shape; the sound is what your mouth does. “C” can sound like K (cat) or S (city). English never promised to be logical — but the patterns are learnable."
            },
            {
                type: "tip",
                title: "The spelling alphabet",
                body: "On the phone, English speakers spell with words: A for Alpha, B for Bravo. Learn 5–6 of them (“M for Mike”) and you can spell anything to anyone."
            },
            {
                type: "practice",
                title: "Write it twice",
                body: "Write your full name, city and email address. Now write them again with correct capitals. Read both out loud, letter by letter."
            }
        ],
        quiz: {
            question: "Which sentence uses capitals correctly?",
            options: [
                "i live in london.",
                "I live in London.",
                "I Live In London."
            ],
            answer: 1,
            explain: "“I” is always capital, city names are capital, everything else stays lowercase."
        }
    },

    /* ---------------- A1 · Reading · unit 1 ---------------- */
    {
        level: "A1", skill: "Reading", unit: 0,
        title: "Word spotting — the 100 most useful words",
        minutes: 12,
        intro: "You don't read every word. You recognise the important ones and let the rest flow past.",
        objectives: [
            "Spot the 20 highest-frequency English words instantly",
            "Guess meaning from context before reaching for a dictionary",
            "Read a sign, menu or message without translating"
        ],
        vocab: [
            { word: "the / a", meaning: "the two most common words in English" },
            { word: "and / or / but", meaning: "connectors — they glue ideas" },
            { word: "is / are / was", meaning: "the “be” family" },
            { word: "you / I / we", meaning: "the people words" }
        ],
        sections: [
            {
                type: "text",
                title: "The 20-word trick",
                body: "Roughly 20 words make up a quarter of everything written in English. If you recognise them on sight — no translating — every text gets faster. Underline them in any English page and watch how much sense appears."
            },
            {
                type: "tip",
                title: "Context beats the dictionary",
                body: "“The train is delayed.” Delayed is new — but trains, times and the word “sorry” above it tell you everything. Guess first, check later."
            },
            {
                type: "practice",
                title: "Spotting hunt",
                body: "Take one English page (a menu works great). Circle every “the, a, and, is, you” you can find in 60 seconds. Count them — this is your new reading speed."
            }
        ],
        quiz: {
            question: "Which word is one of the most frequent in English?",
            options: ["elephant", "the", "yesterday"],
            answer: 1,
            explain: "“The” is the single most common English word — you'll see it everywhere."
        }
    },

    /* ---------------- A1 · Listening · unit 1 ---------------- */
    {
        level: "A1", skill: "Listening", unit: 0,
        title: "Ear training — sounds of English",
        minutes: 13,
        intro: "English has sounds your language may not have. Train the ear and the mouth follows.",
        objectives: [
            "Hear the difference between ship and sheep",
            "Hear word endings (-s, -ed) that carry meaning",
            "Shadow a slow dialogue line by line"
        ],
        vocab: [
            { word: "ship / sheep", meaning: "the classic short vs long “i” pair" },
            { word: "walked", meaning: "the -ed ending sounds like “t”" },
            { word: "played", meaning: "the -ed ending sounds like “d”" }
        ],
        sections: [
            {
                type: "text",
                title: "Why endings matter",
                body: "“I walk” and “I walked” differ by one tiny sound — but one is present, one is past. English puts a lot of meaning into quiet endings. Your ear must learn to catch them."
            },
            {
                type: "tip",
                title: "Shadowing",
                body: "Play one slow sentence. Listen once. Now say it along with the speaker, same rhythm, same melody. Repeat three times. This is how interpreters train."
            },
            {
                type: "practice",
                title: "Ten-minute ear workout",
                body: "Find any slow English audio. Shadow 5 sentences. Then write down every word ending you can hear. Check yourself — did you catch the -s and -ed?"
            }
        ],
        quiz: {
            question: "The word “played” ends with a sound like…",
            options: ["t", "d", "ed"],
            answer: 1,
            explain: "After voiced sounds, -ed is pronounced like “d”: play → played."
        }
    },

    /* ---------------- B1 · Speaking · unit 1 ---------------- */
    {
        level: "B1", skill: "Speaking", unit: 0,
        title: "Opinions — agree, disagree, explain why",
        minutes: 15,
        intro: "B1 is where you stop answering and start discussing. The secret: structure.",
        objectives: [
            "Give an opinion with a reason and an example",
            "Disagree politely, then offer an alternative",
            "Keep the discussion moving with follow-up questions"
        ],
        vocab: [
            { word: "I'd say that…", meaning: "soft, confident opinion opener" },
            { word: "I see your point, but…", meaning: "polite disagreement" },
            { word: "That's a fair point", meaning: "acknowledge before you counter" }
        ],
        sections: [
            {
                type: "text",
                title: "The three-part opinion",
                body: "Fluent speakers follow a shape: opinion → reason → example. “I'd say remote work helps (opinion) because people focus better at home (reason) — for example, I finish writing tasks twice as fast (example).” Short, complete, persuasive."
            },
            {
                type: "tip",
                title: "Disagree with the idea, not the person",
                body: "“I see your point, but…” keeps the conversation warm. Attack the argument, never the speaker — and always add what you think instead."
            },
            {
                type: "practice",
                title: "The two-minute debate",
                body: "Pick a simple topic (homework should be optional). Speak for one minute: opinion, reason, example. Then switch sides and argue the opposite. Both sides make you flexible."
            }
        ],
        quiz: {
            question: "Which reply disagrees politely?",
            options: [
                "You're wrong about that.",
                "I see your point, but I'd say the opposite.",
                "No. Next question."
            ],
            answer: 1,
            explain: "Acknowledge first (“I see your point”), then add your view (“but I'd say…”)."
        }
    },

    /* ---------------- B1 · Writing · unit 1 ---------------- */
    {
        level: "B1", skill: "Writing", unit: 0,
        title: "Structuring texts — intro, body, ending",
        minutes: 15,
        intro: "A B1 text isn't longer than an A2 text. It's built. Three parts, one idea each.",
        objectives: [
            "Open with a sentence that promises something",
            "Develop ONE idea per paragraph with a linking word",
            "End with a conclusion, not a repetition"
        ],
        vocab: [
            { word: "However", meaning: "contrast linker — formal" },
            { word: "As a result", meaning: "consequence linker" },
            { word: "To sum up", meaning: "conclusion opener" }
        ],
        sections: [
            {
                type: "text",
                title: "The promise sandwich",
                body: "Intro makes a promise (“This week taught me two things”). Body delivers them, one paragraph each. Conclusion answers the promise — what does it all mean? If your ending repeats the intro word for word, you haven't concluded yet."
            },
            {
                type: "tip",
                title: "Link, don't list",
                body: "“Also, also, also” sounds like a shopping list. “However”, “as a result”, “in addition” turn sentences into an argument. One linker per paragraph is enough."
            },
            {
                type: "practice",
                title: "The 100-word build",
                body: "Write 100 words about “The best app I use”. Sentence 1 promises. Two body paragraphs, one idea each with a linker. Final sentence concludes. Count the words — no more, no less."
            }
        ],
        quiz: {
            question: "What makes a strong final sentence?",
            options: [
                "It repeats the introduction",
                "It concludes from the body's ideas",
                "It introduces a brand-new topic"
            ],
            answer: 1,
            explain: "A conclusion pulls the body's ideas together — it never introduces something new."
        }
    }
];

/* find the authored lesson for one unit (or null) */
function authoredLesson(levelId, skillName, unitIndex) {
    return LESSON_LIBRARY.find(l =>
        l.level === levelId && l.skill === skillName && l.unit === unitIndex) || null;
}
